name: Restaurant API CI

on:
  push:
    branches:
      - development/ef-core
  pull_request:
    branches:
      - development/ef-core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore RestaurantWebAPIProject.sln

      - name: Build
        run: dotnet build RestaurantWebAPIProject.sln --no-restore

      - name: Build Docker image
        run: docker build -t restaurant-api -f RestaurantWebAPIProject/Dockerfile .

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login restaurantapipriya.azurecr.io \
            --username "${{ secrets.ACR_USERNAME }}" \
            --password-stdin

      - name: Tag Docker image
        run: docker tag restaurant-api:latest restaurantapipriya.azurecr.io/restaurant-api:latest

      - name: Push Docker image to ACR
        run: docker push restaurantapipriya.azurecr.io/restaurant-api:latest        
        
