name: Restaurant API CI

on:
  push:
    branches:
      - development/ef-core
  pull_request:
    branches:
      - development/ef-core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore RestaurantWebAPIProject.sln

      - name: Build
        run: dotnet build RestaurantWebAPIProject.sln --no-restore